<a href="https://colab.research.google.com/github/polymathicneo/ML-Foundations/blob/main/DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

Creating a DataFrame

In [3]:
data = {
    'Name' : ['John', 'Anna', 'Peter', 'Linda'],
    'Age' :  [28, 34, 29, 42],
    'City' : ['New York', 'Paris', 'Berlin', 'London'],
    'Salary' : [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [4]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]

]
df2 = pd.DataFrame(data_list)
columns = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns= columns)

In [6]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and indexing of columns

In [7]:
df[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [8]:
df2["Designation"] = ["doctor", "engineer", "doctor", "Eng"]

In [9]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000    engineer
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000         Eng

Removing Column

In [10]:
df2.drop("Designation", axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selecting rows

In [11]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000    engineer
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000         Eng

In [12]:
df2.drop("Designation", axis = 1, inplace = True)

In [13]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [14]:
df2.drop(["City", "Salary"], axis = 1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [15]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [16]:
df2.drop(["City", "Age"], axis=1)

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

**Removing Rows from dataframes**

In [17]:
df2.drop(0, axis = 0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

**Selecting Rows**

In [18]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [21]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [22]:
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

**Selecting Subsets of Rows and columns**

In [23]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [26]:
df.loc[[0,1]], [['City', 'Salary']]

(   Name  Age      City  Salary
 0  John   28  New York   65000
 1  Anna   34     Paris   70000,
 [['City', 'Salary']])

In [27]:
df.loc[[2,3]]

    Name  Age    City  Salary
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

Conditional Selection

In [31]:
df2[df2["Age"] > 30 ]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [32]:
df2[(df2["Age"] > 30 ) & (df2["City"] =="London")]

    Name  Age    City  Salary
3  Linda   42  London   85000